# USE WITH CAUTION: Still under construction

https://towardsdatascience.com/pandas-and-sql-together-a-premier-league-and-player-scouting-example-b41713a5dd3e

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
user = input('videosurvey DB user name:')
password = input('videosurvey DB password:')
engine = create_engine(f'mysql+pymysql://{user}:{password}@mysql.guaminsects.net/videosurvey')
engine.connect() # test connection

videosurvey DB user name:aubreymoore
videosurvey DB password:Canada_12

# Create objects table
df = pd.read_csv('video_settings.csv')
connection = engine.connect()
df.to_sql(con=connection, name='video')

In [5]:
# Read objects table from CSV
df = pd.read_csv('/media/aubrey/9C33-6BBD/20200703_125239_AI/20200703_125239_gps_obs.csv')
df['video_file'] = '20200703_125239.mp4'
df

,frame,keyframe,xtl,ytl,xbr,ybr,track_id,label,timestamp,lat,lon,damage,video_file
0,135,1,188,1359,274,1431,0,none,2020-07-03 02:53:54.847778,13.577067,144.893685,0,20200703_125239.mp4
1,136,1,189,1358,279,1429,1,none,2020-07-03 02:53:54.881100,13.577072,144.893682,0,20200703_125239.mp4
2,141,1,170,1361,265,1444,2,none,2020-07-03 02:53:55.047722,13.577098,144.893663,0,20200703_125239.mp4
3,145,1,158,1362,243,1435,3,none,2020-07-03 02:53:55.181033,13.577118,144.893648,0,20200703_125239.mp4
4,148,1,153,1360,241,1432,4,none,2020-07-03 02:53:55.281011,13.577133,144.893637,0,20200703_125239.mp4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7452,20830,1,855,1263,968,1352,7452,none,2020-07-03 03:05:27.370422,13.532686,144.827133,0,20200703_125239.mp4
7453,21099,1,10,1308,113,1399,7453,none,2020-07-03 03:05:36.401767,13.531426,144.826557,0,20200703_125239.mp4
7454,21100,1,9,1314,109,1403,7454,none,2020-07-03 03:05:36.435100,13.531421,144.826555,0,20200703_125239.mp4
7455,21101,1,9,1311,100,1399,7455,none,2020-07-03 03:05:36.468422,13.531416,144.826552,0,20200703_125239.mp4
7456,21106,1,3,1289,92,1396,7456,none,2020-07-03 03:05:36.635056,13.531391,144.826541,0,20200703_125239.mp4

In [6]:
# Read objects table from MySQL
connection = engine.connect()
df = pd.read_sql_table('objects', engine)
df

/home/aubrey/.virtualenvs/py_37_env/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/reflection.py:193: SAWarning: Did not recognize type 'point' of column 'coords'
  "Did not recognize type '%s' of column '%s'" % (type_, name)

,frame,keyframe,xtl,ytl,xbr,ybr,track_id,label,timestamp,lat,lon,damage,video_file,coords
0,135,1,188,1359,274,1431,0,none,2020-07-03 02:53:54.847778,13.577067,144.893685,0,20200703_125239.mp4,"b""\x00\x00\x00\x00\x01\x01\x00\x00\x00\xda\xee..."
1,136,1,189,1358,279,1429,1,none,2020-07-03 02:53:54.881100,13.577072,144.893682,0,20200703_125239.mp4,"b""\x00\x00\x00\x00\x01\x01\x00\x00\x00\x7f\xc9..."
2,141,1,170,1361,265,1444,2,none,2020-07-03 02:53:55.047722,13.577098,144.893663,0,20200703_125239.mp4,"b""\x00\x00\x00\x00\x01\x01\x00\x00\x00e&+\xe3\..."
3,145,1,158,1362,243,1435,3,none,2020-07-03 02:53:55.181033,13.577118,144.893648,0,20200703_125239.mp4,"b""\x00\x00\x00\x00\x01\x01\x00\x00\x00\xab`\xe..."
4,148,1,153,1360,241,1432,4,none,2020-07-03 02:53:55.281011,13.577133,144.893637,0,20200703_125239.mp4,"b""\x00\x00\x00\x00\x01\x01\x00\x00\x00'\x1dl\x..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10838,112,1,2411,687,2839,1362,30,medium,2020-07-03 02:41:58.081567,13.543890,144.913036,2,temp.mp4,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\x1d\xf3...
10839,119,1,2989,490,3640,1391,31,medium,2020-07-03 02:41:58.314878,13.543928,144.913045,2,temp.mp4,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\xdd\xcf...
10840,126,1,3643,545,3838,1042,32,high,2020-07-03 02:41:58.548178,13.543966,144.913055,3,temp.mp4,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\xefly\x...
10841,385,1,2575,591,2715,747,0,light,2020-07-03 03:29:50.069600,13.431558,144.781728,1,20200703_132826.mp4,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\x0fK=\x...
10842,588,1,3501,544,3618,930,1,high,2020-07-03 03:29:56.834878,13.430570,144.782035,3,20200703_132826.mp4,b'\x00\x00\x00\x00\x01\x01\x00\x00\x00\x94T\x8...

In [10]:
# Add a CSV to the MySQL objects table
CSV = '/media/aubrey/9C33-6BBD/20200630_132859/20200630_132859_gps_obs.csv'
VIDEO = '20200630_132859.mp4'
df = pd.read_csv(CSV)
df['video_file'] = VIDEO
df

,frame,keyframe,xtl,ytl,xbr,ybr,track_id,label,timestamp,lat,lon,damage,video_file
0,88,1,1610,1084,1994,1464,0,none,2020-06-30 03:30:13.347078,13.404784,144.691951,0,20200630_132859.mp4
1,90,1,1652,1053,2063,1435,1,none,2020-06-30 03:30:13.413733,13.404783,144.691940,0,20200630_132859.mp4
2,92,1,1680,1031,2127,1441,2,none,2020-06-30 03:30:13.480389,13.404783,144.691930,0,20200630_132859.mp4
3,183,1,1189,1269,1268,1350,3,medium,2020-06-30 03:30:16.513233,13.404760,144.691444,2,20200630_132859.mp4
4,188,1,1179,1268,1258,1351,4,medium,2020-06-30 03:30:16.679867,13.404759,144.691418,2,20200630_132859.mp4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3334,2079,1,2253,1264,2362,1433,3334,low,2020-06-30 03:31:19.933244,13.403433,144.688190,1,20200630_132859.mp4
3335,2079,1,2345,1293,2465,1425,3335,medium,2020-06-30 03:31:19.933244,13.403433,144.688190,2,20200630_132859.mp4
3336,2079,1,2011,1162,2162,1471,3336,low,2020-06-30 03:31:19.933244,13.403433,144.688190,1,20200630_132859.mp4
3337,2080,1,2010,1163,2159,1457,3337,low,2020-06-30 03:31:19.966578,13.403433,144.688190,1,20200630_132859.mp4
3338,2080,1,2252,1265,2364,1420,3338,low,2020-06-30 03:31:19.966578,13.403433,144.688190,1,20200630_132859.mp4

In [12]:
df.to_sql('objects', connection, if_exists='append', index=False)

InternalError: (pymysql.err.InternalError) (1416, 'Cannot get geometry object from data you send to the GEOMETRY field')
[SQL: INSERT INTO objects (frame, keyframe, xtl, ytl, xbr, ybr, track_id, label, timestamp, lat, lon, damage, video_file) VALUES (%(frame)s, %(keyframe)s, %(xtl)s, %(ytl)s, %(xbr)s, %(ybr)s, %(track_id)s, %(label)s, %(timestamp)s, %(lat)s, %(lon)s, %(damage)s, %(video_file)s)]
[parameters: ({'frame': 88, 'keyframe': 1, 'xtl': 1610, 'ytl': 1084, 'xbr': 1994, 'ybr': 1464, 'track_id': 0, 'label': 'none', 'timestamp': '2020-06-30 03:30:13.347078', 'lat': 13.40478362760022, 'lon': 144.69195112714328, 'damage': 0, 'video_file': '20200630_132859.mp4'}, {'frame': 90, 'keyframe': 1, 'xtl': 1652, 'ytl': 1053, 'xbr': 2063, 'ybr': 1435, 'track_id': 1, 'label': 'none', 'timestamp': '2020-06-30 03:30:13.413733', 'lat': 13.40478326033117, 'lon': 144.6919403796911, 'damage': 0, 'video_file': '20200630_132859.mp4'}, {'frame': 92, 'keyframe': 1, 'xtl': 1680, 'ytl': 1031, 'xbr': 2127, 'ybr': 1441, 'track_id': 2, 'label': 'none', 'timestamp': '2020-06-30 03:30:13.480389', 'lat': 13.404782893056607, 'lon': 144.69192963207763, 'damage': 0, 'video_file': '20200630_132859.mp4'}, {'frame': 183, 'keyframe': 1, 'xtl': 1189, 'ytl': 1269, 'xbr': 1268, 'ybr': 1350, 'track_id': 3, 'label': 'medium', 'timestamp': '2020-06-30 03:30:16.513233', 'lat': 13.40476011375718, 'lon': 144.69144411314554, 'damage': 2, 'video_file': '20200630_132859.mp4'}, {'frame': 188, 'keyframe': 1, 'xtl': 1179, 'ytl': 1268, 'xbr': 1258, 'ybr': 1351, 'track_id': 4, 'label': 'medium', 'timestamp': '2020-06-30 03:30:16.679867', 'lat': 13.40475852406882, 'lon': 144.69141752002545, 'damage': 2, 'video_file': '20200630_132859.mp4'}, {'frame': 201, 'keyframe': 1, 'xtl': 1104, 'ytl': 1261, 'xbr': 1197, 'ybr': 1354, 'track_id': 5, 'label': 'medium', 'timestamp': '2020-06-30 03:30:17.113100', 'lat': 13.404755753880998, 'lon': 144.691348823723, 'damage': 2, 'video_file': '20200630_132859.mp4'}, {'frame': 202, 'keyframe': 1, 'xtl': 1105, 'ytl': 1252, 'xbr': 1200, 'ybr': 1346, 'track_id': 6, 'label': 'medium', 'timestamp': '2020-06-30 03:30:17.146422', 'lat': 13.404755837519224, 'lon': 144.69134363648726, 'damage': 2, 'video_file': '20200630_132859.mp4'}, {'frame': 203, 'keyframe': 1, 'xtl': 1444, 'ytl': 1061, 'xbr': 1730, 'ybr': 1362, 'track_id': 7, 'label': 'low', 'timestamp': '2020-06-30 03:30:17.179744', 'lat': 13.404755921157436, 'lon': 144.6913384492515, 'damage': 1, 'video_file': '20200630_132859.mp4'}  ... displaying 10 of 3339 total bound parameter sets ...  {'frame': 2080, 'keyframe': 1, 'xtl': 2010, 'ytl': 1163, 'xbr': 2159, 'ybr': 1457, 'track_id': 3337, 'label': 'low', 'timestamp': '2020-06-30 03:31:19.966578', 'lat': 13.40343315, 'lon': 144.68819014, 'damage': 1, 'video_file': '20200630_132859.mp4'}, {'frame': 2080, 'keyframe': 1, 'xtl': 2252, 'ytl': 1265, 'xbr': 2364, 'ybr': 1420, 'track_id': 3338, 'label': 'low', 'timestamp': '2020-06-30 03:31:19.966578', 'lat': 13.40343315, 'lon': 144.68819014, 'damage': 1, 'video_file': '20200630_132859.mp4'})]
(Background on this error at: http://sqlalche.me/e/2j85)

In [ ]:
UPDATE table_name SET coord = POINT(longitude_field, latitude_field);

# Workaround

https://stackoverflow.com/questions/42672807/insert-geometry-point-mysql-from-pandas-dataframe

A work around is to create a temporary table with the String of the geometrical information that need to be added and then update the point_test table with a call to ST_GeomFromText from the temporary table.

Assuming database with table point_test with id (VARCHAR(5)) and coords(POINT):

a.Create dataframe df as an example with point "A" and "B"

In [14]:
import numpy as np

dfd = np.array([['id','geomText'],
            ["A","POINT( 50.2 5.6 )"],
            ["B","POINT( 50.2 50.4 )"]])
df=pd.DataFrame(data=dfd[1:,:], columns=dfd[0,:])

b.Add point "A" and "B" into point_test but only the id and add the string "geomText" into the table temp_point_test

In [15]:
df[['id']].to_sql("point_test",engine, index=False, if_exists="append")
df[['id', 'geomText']].to_sql("temp_point_test",engine, index=False, if_exists="append")

c. Update table point_test with the point from table temp_point_test applying the ST_GeomFromText() to the select. Finally, drop temp_point_test:

In [19]:
conn = engine.connect()

In [20]:
conn.execute('ALTER TABLE point_test ADD coords POINT')

InternalError: (pymysql.err.InternalError) (1060, "Duplicate column name 'coords'")
[SQL: ALTER TABLE point_test ADD coords POINT]
(Background on this error at: http://sqlalche.me/e/2j85)

In [21]:
conn.execute("update point_test pt set pt.coords=(select ST_GeomFromText(geomText) from temp_point_test tpt "+
                     "where pt.id=tpt.id)")

In [22]:
conn.execute("drop table temp_point_test")

In [23]:
conn.close()

# My Workaround

In [2]:
# Add a CSV to the MySQL objects table
# Includes a workaround to create geometry column (coords) so that QGIS can plot points on a map

import pandas as pd
from sqlalchemy import create_engine

CSV = '/media/aubrey/9C33-6BBD/20200630_132859/20200630_132859_gps_obs.csv'
VIDEO = '20200630_132859.mp4'
USER = 'savan'
PASSWORD = 'oryctes_rhinoceros'

engine = create_engine(f'mysql+pymysql://{USER}:{PASSWORD}@mysql.guaminsects.net/videosurvey')

df = pd.read_csv(CSV)
df['video_file'] = VIDEO
conn = engine.connect()
conn.execute('DROP TABLE IF EXISTS temp;')
df.to_sql("temp", engine, index=False, if_exists="replace")

conn.execute('ALTER TABLE temp ADD coords POINT;')
conn.execute('UPDATE temp SET coords=POINT(lon,lat);')
conn.execute('INSERT INTO objects SELECT * FROM temp;')
conn.close()

/home/aubrey/.virtualenvs/py_37_env/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1051, "Unknown table 'videosurvey.temp'")
  result = self._query(query)

IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '20200630_132859.mp4-88-1994-1610-1464-1084' for key 'video_file_2'")
[SQL: INSERT INTO objects SELECT * FROM temp;]
(Background on this error at: http://sqlalche.me/e/gkpj)

In [5]:
df

,frame,keyframe,xtl,ytl,xbr,ybr,track_id,label,timestamp,lat,lon,damage,video_file
0,88,1,1610,1084,1994,1464,0,none,2020-06-30 03:30:13.347078,13.404784,144.691951,0,20200630_132859.mp4
1,90,1,1652,1053,2063,1435,1,none,2020-06-30 03:30:13.413733,13.404783,144.691940,0,20200630_132859.mp4
2,92,1,1680,1031,2127,1441,2,none,2020-06-30 03:30:13.480389,13.404783,144.691930,0,20200630_132859.mp4
3,183,1,1189,1269,1268,1350,3,medium,2020-06-30 03:30:16.513233,13.404760,144.691444,2,20200630_132859.mp4
4,188,1,1179,1268,1258,1351,4,medium,2020-06-30 03:30:16.679867,13.404759,144.691418,2,20200630_132859.mp4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3334,2079,1,2253,1264,2362,1433,3334,low,2020-06-30 03:31:19.933244,13.403433,144.688190,1,20200630_132859.mp4
3335,2079,1,2345,1293,2465,1425,3335,medium,2020-06-30 03:31:19.933244,13.403433,144.688190,2,20200630_132859.mp4
3336,2079,1,2011,1162,2162,1471,3336,low,2020-06-30 03:31:19.933244,13.403433,144.688190,1,20200630_132859.mp4
3337,2080,1,2010,1163,2159,1457,3337,low,2020-06-30 03:31:19.966578,13.403433,144.688190,1,20200630_132859.mp4
3338,2080,1,2252,1265,2364,1420,3338,low,2020-06-30 03:31:19.966578,13.403433,144.688190,1,20200630_132859.mp4